### PR TITLE
Fix label printing error message

### LINKED ISSUE #394: Y24-369 - [BUG] Missing squix template results in 422 with no error message
**Describe the bug**
A missing squix template results in a 422 error with an empty errors array. We should have a clear error message returned to assist diagnosis.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

### PR DESCRIPTION
**Pull request by dasunpubudumal**
Closes #394 

#### Changes proposed in this pull request

- Fixing diagnosis message for when the templates aren't found. 

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

### CODE REVIEW

File: spec/models/print_job_wrapper_spec.rb [hunk 1]
```diff
@@ -91,6 +91,13 @@
         expect(print_job_wrapper).to be_valid
         expect(print_job_wrapper.print).to be_truthy
       end
+
+      it 'raises a StandardError with a 422 status code if label_template validation fails' do
```
Comment (BenTopping) [inline spec/models/print_job_wrapper_spec.rb:95]: 'will not execute if the label template does not exist' probably a better test name as this isn't producing a standard error or 422

**Review by BenTopping — COMMENTED** [review]
Looks good.

**Review by BenTopping — APPROVED** [review]
